### ISSUE TITLE
Can we use the same components as in React Native?

### ISSUE THREAD

**Issue by amaurymartiny** [shootismoke/webapp#2]
https://docs.expo.io/versions/v35.0.0/guides/running-in-the-browser/

Could we use some of the components from React Native directly in browser? I'm thinking about the `Cigarettes` component

cc @florenciasilva

**Comment by florenciasilva** [comment]
Sure! This would be to avoid re-writing it?

**Comment by amaurymartiny** [comment]
Yeah, exactly.

**Comment by amaurymartiny** [comment]
This is done, see https://github.com/shootismoke/common/tree/master/packages/ui
